using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Threading;
using Pixora.Avalonia.ViewModels;
using Pixora.Core.Models;

namespace Pixora.Avalonia.Views.Artwork;

public partial class ArtworkViewerWindow : Window
{
    private double _scale = 1.0;
    private double _translateX, _translateY;
    private bool _isPanning;
    private Point _panStart;
    private double _panStartX, _panStartY;

    public ArtworkViewerWindow() { InitializeComponent(); }

    public ArtworkViewerWindow(ArtworkPreview artwork, GalleryViewModel gallery)
    {
        InitializeComponent();
        var vm = new ArtworkViewerViewModel(artwork, gallery, this);
        DataContext = vm;

        // Zoom toolbar — named fields auto-generated by Avalonia source generator
        PopupZoomInBtn.Click  += (_, _) => ZoomAround(1.25);
        PopupZoomOutBtn.Click += (_, _) => ZoomAround(1.0 / 1.25);
        PopupZoomFitBtn.Click += (_, _) => ResetZoom();

        // Pointer events on canvas
        PopupCanvas.PointerWheelChanged += OnWheel;
        PopupCanvas.PointerPressed      += OnPressed;
        PopupCanvas.PointerMoved        += OnMoved;
        PopupCanvas.PointerReleased     += OnReleased;

        // When bitmap changes, update resolution label and reset zoom
        vm.PropertyChanged += (_, e) =>
        {
            if (e.PropertyName == nameof(ArtworkViewerViewModel.CurrentPageBitmap))
                Dispatcher.UIThread.Post(OnBitmapChanged);
        };

        _ = vm.LoadFirstPageAsync();
    }

    private void OnBitmapChanged()
    {
        if (PopupImage?.Source is Bitmap bmp)
        {
            if (PopupResLabel != null)
                PopupResLabel.Text = $"{bmp.PixelSize.Width}×{bmp.PixelSize.Height}";
        }
        ResetZoom();
    }

    private void ApplyTransform()
    {
        if (PopupImage == null) return;
        PopupImage.RenderTransform = new TransformGroup
        {
            Children =
            [
                new ScaleTransform(_scale, _scale),
                new TranslateTransform(_translateX, _translateY)
            ]
        };
        if (PopupZoomLabel != null)
            PopupZoomLabel.Text = $"{_scale * 100:F0}%";
    }

    private void ResetZoom()
    {
        _scale = 1.0; _translateX = 0; _translateY = 0;
        ApplyTransform();
    }

    private void ZoomAround(double factor)
    {
        if (PopupCanvas == null) return;
        var cx = PopupCanvas.Bounds.Width  / 2;
        var cy = PopupCanvas.Bounds.Height / 2;
        _translateX = cx - (cx - _translateX) * factor;
        _translateY = cy - (cy - _translateY) * factor;
        _scale = System.Math.Clamp(_scale * factor, 0.05, 20.0);
        ApplyTransform();
    }

    private void OnWheel(object? sender, PointerWheelEventArgs e)
    {
        if (PopupCanvas == null) return;
        var factor = e.Delta.Y > 0 ? 1.15 : 1.0 / 1.15;
        var pos = e.GetPosition(PopupCanvas);
        _translateX = pos.X - (pos.X - _translateX) * factor;
        _translateY = pos.Y - (pos.Y - _translateY) * factor;
        _scale = System.Math.Clamp(_scale * factor, 0.05, 20.0);
        ApplyTransform();
        e.Handled = true;
    }

    private void OnPressed(object? sender, PointerPressedEventArgs e)
    {
        if (!e.GetCurrentPoint(null).Properties.IsLeftButtonPressed) return;
        _isPanning = true;
        _panStart  = e.GetPosition(PopupCanvas);
        _panStartX = _translateX;
        _panStartY = _translateY;
        e.Handled  = true;
    }

    private void OnMoved(object? sender, PointerEventArgs e)
    {
        if (!_isPanning || PopupCanvas == null) return;
        var pos = e.GetPosition(PopupCanvas);
        _translateX = _panStartX + (pos.X - _panStart.X);
        _translateY = _panStartY + (pos.Y - _panStart.Y);
        ApplyTransform();
    }

    private void OnReleased(object? sender, PointerReleasedEventArgs e) => _isPanning = false;
}
